# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Piiaf' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'StreamingKit', '~> 0.1.25'
  # Pods for Piiaf

  target 'PiiafTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
